// Generated by: pnpm supabase gen types typescript --project-id <ref> > packages/supabase/src/types.ts
// Do not edit manually — re-run the command above after schema changes.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
